/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ceofyeast.stringgameengine.screeneditor;

/**
 *
 * @author bento
 */
public class ScreenEditorJframeTesting extends javax.swing.JFrame {

  /**
   * Creates new form ScreenEditorJframeTesting
   */
  public ScreenEditorJframeTesting() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    newGamePanel = new javax.swing.JPanel();
    newGameInfoTip = new javax.swing.JLabel();
    optionsPanel = new javax.swing.JPanel();
    nameOption = new javax.swing.JPanel();
    nameLabel = new javax.swing.JLabel();
    nameField = new javax.swing.JTextField();
    buttonPanel = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    menuBar = new javax.swing.JMenuBar();
    fileMenu = new javax.swing.JMenu();
    loadGame = new javax.swing.JMenu();
    newGame = new javax.swing.JMenuItem();
    deleteGame = new javax.swing.JMenuItem();
    gameAndScreenSeperator = new javax.swing.JPopupMenu.Separator();
    loadScreen = new javax.swing.JMenu();
    newScreen = new javax.swing.JMenuItem();
    saveScreen = new javax.swing.JMenuItem();
    deleteScreen = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    newGamePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
    newGamePanel.setToolTipText("");
    newGamePanel.setPreferredSize(new java.awt.Dimension(320, 214));
    newGamePanel.setLayout(new java.awt.GridLayout(0, 1));

    newGameInfoTip.setBackground(new java.awt.Color(51, 153, 255));
    newGameInfoTip.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    newGameInfoTip.setForeground(new java.awt.Color(255, 255, 255));
    newGameInfoTip.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    newGameInfoTip.setText("Enter New Game Info.");
    newGameInfoTip.setAlignmentX(0.5F);
    newGameInfoTip.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
    newGameInfoTip.setOpaque(true);
    newGamePanel.add(newGameInfoTip);

    optionsPanel.setPreferredSize(new java.awt.Dimension(278, 0));
    optionsPanel.setLayout(new java.awt.GridLayout(0, 1));

    nameOption.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 10));

    nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    nameLabel.setText("Name:");
    nameLabel.setPreferredSize(new java.awt.Dimension(70, 16));
    nameOption.add(nameLabel);

    nameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    nameField.setText("jTextField1");
    nameField.setPreferredSize(new java.awt.Dimension(140, 16));
    nameField.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        nameFieldActionPerformed(evt);
      }
    });
    nameOption.add(nameField);

    optionsPanel.add(nameOption);

    newGamePanel.add(optionsPanel);

    buttonPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(153, 153, 153)));
    java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
    flowLayout1.setAlignOnBaseline(true);
    buttonPanel.setLayout(flowLayout1);

    jButton1.setText("Submit");
    jButton1.setPreferredSize(new java.awt.Dimension(75, 25));
    buttonPanel.add(jButton1);

    jButton2.setText("Cancel");
    jButton2.setPreferredSize(new java.awt.Dimension(75, 25));
    buttonPanel.add(jButton2);

    newGamePanel.add(buttonPanel);

    fileMenu.setText("File");

    loadGame.setText("Load Game");
    fileMenu.add(loadGame);

    newGame.setText("New Game");
    newGame.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        newGameActionPerformed(evt);
      }
    });
    fileMenu.add(newGame);

    deleteGame.setText("Delete Game");
    fileMenu.add(deleteGame);
    fileMenu.add(gameAndScreenSeperator);

    loadScreen.setText("Load Screen");
    fileMenu.add(loadScreen);

    newScreen.setText("New Screen");
    newScreen.setToolTipText("NewScreen");
    newScreen.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        newScreenActionPerformed(evt);
      }
    });
    fileMenu.add(newScreen);

    saveScreen.setText("Save Screen");
    saveScreen.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        saveScreenActionPerformed(evt);
      }
    });
    fileMenu.add(saveScreen);

    deleteScreen.setText("Delete Screen");
    deleteScreen.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        deleteScreenActionPerformed(evt);
      }
    });
    fileMenu.add(deleteScreen);

    menuBar.add(fileMenu);

    setJMenuBar(menuBar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(40, 40, 40)
        .addComponent(newGamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(52, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(newGamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(141, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void saveScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveScreenActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_saveScreenActionPerformed

  private void newScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newScreenActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_newScreenActionPerformed

  private void deleteScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteScreenActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_deleteScreenActionPerformed

  private void newGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameActionPerformed
    // TODO add your handling code here:
    
  }//GEN-LAST:event_newGameActionPerformed

  private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_nameFieldActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(ScreenEditorJframeTesting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(ScreenEditorJframeTesting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(ScreenEditorJframeTesting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(ScreenEditorJframeTesting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new ScreenEditorJframeTesting().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel buttonPanel;
  private javax.swing.JMenuItem deleteGame;
  private javax.swing.JMenuItem deleteScreen;
  private javax.swing.JMenu fileMenu;
  private javax.swing.JPopupMenu.Separator gameAndScreenSeperator;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JMenu loadGame;
  private javax.swing.JMenu loadScreen;
  private javax.swing.JMenuBar menuBar;
  private javax.swing.JTextField nameField;
  private javax.swing.JLabel nameLabel;
  private javax.swing.JPanel nameOption;
  private javax.swing.JMenuItem newGame;
  private javax.swing.JLabel newGameInfoTip;
  private javax.swing.JPanel newGamePanel;
  private javax.swing.JMenuItem newScreen;
  private javax.swing.JPanel optionsPanel;
  private javax.swing.JMenuItem saveScreen;
  // End of variables declaration//GEN-END:variables
}
