/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ceofyeast.stringgameengine.screeneditor;

/**
 *
 * @author bento
 */
public class ScreenEditorJframeTesting extends javax.swing.JFrame {

  /**
   * Creates new form ScreenEditorJframeTesting
   */
  public ScreenEditorJframeTesting() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    menuBar = new javax.swing.JMenuBar();
    fileMenu = new javax.swing.JMenu();
    loadGame = new javax.swing.JMenu();
    jSeparator1 = new javax.swing.JPopupMenu.Separator();
    loadScreen = new javax.swing.JMenu();
    newScreen = new javax.swing.JMenuItem();
    saveScreen = new javax.swing.JMenuItem();
    deleteScreen = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    fileMenu.setText("File");

    loadGame.setText("Load Game");
    fileMenu.add(loadGame);
    fileMenu.add(jSeparator1);

    loadScreen.setText("Load Screen");
    fileMenu.add(loadScreen);

    newScreen.setText("New Screen");
    newScreen.setToolTipText("NewScreen");
    newScreen.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        newScreenActionPerformed(evt);
      }
    });
    fileMenu.add(newScreen);

    saveScreen.setText("Save Screen");
    saveScreen.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        saveScreenActionPerformed(evt);
      }
    });
    fileMenu.add(saveScreen);

    deleteScreen.setText("Delete Screen");
    deleteScreen.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        deleteScreenActionPerformed(evt);
      }
    });
    fileMenu.add(deleteScreen);

    menuBar.add(fileMenu);

    setJMenuBar(menuBar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 277, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void saveScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveScreenActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_saveScreenActionPerformed

  private void newScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newScreenActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_newScreenActionPerformed

  private void deleteScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteScreenActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_deleteScreenActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(ScreenEditorJframeTesting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(ScreenEditorJframeTesting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(ScreenEditorJframeTesting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(ScreenEditorJframeTesting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new ScreenEditorJframeTesting().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenuItem deleteScreen;
  private javax.swing.JMenu fileMenu;
  private javax.swing.JPopupMenu.Separator jSeparator1;
  private javax.swing.JMenu loadGame;
  private javax.swing.JMenu loadScreen;
  private javax.swing.JMenuBar menuBar;
  private javax.swing.JMenuItem newScreen;
  private javax.swing.JMenuItem saveScreen;
  // End of variables declaration//GEN-END:variables
}
