/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ceofyeast.stringgameengine.screeneditor;

import java.io.File;  
import java.io.IOException;

/**
 *
 * @author bento
 */
public class ScreenEditorJframeTesting extends javax.swing.JFrame {

  /**
   * Creates new form ScreenEditorJframeTesting
   */
  public ScreenEditorJframeTesting() {
    initComponents();
    
    newGamePanel.setVisible( false );
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    newGamePanel = new javax.swing.JPanel();
    infoTip_newGame = new javax.swing.JLabel();
    optionsPanel_newGame = new javax.swing.JPanel();
    nameOption_newGame = new javax.swing.JPanel();
    nameFieldLabel_newGame = new javax.swing.JLabel();
    nameField_newGame = new javax.swing.JTextField();
    submissionButtonPanel_newGame = new javax.swing.JPanel();
    submitButton__newGame = new javax.swing.JButton();
    cancelButton_newGame = new javax.swing.JButton();
    menuBar = new javax.swing.JMenuBar();
    fileMenu = new javax.swing.JMenu();
    loadGame = new javax.swing.JMenu();
    newGame = new javax.swing.JMenuItem();
    deleteGame = new javax.swing.JMenuItem();
    gameAndScreenSeperator = new javax.swing.JPopupMenu.Separator();
    loadScreen = new javax.swing.JMenu();
    newScreen = new javax.swing.JMenuItem();
    saveScreen = new javax.swing.JMenuItem();
    deleteScreen = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    newGamePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
    newGamePanel.setToolTipText("");
    newGamePanel.setPreferredSize(new java.awt.Dimension(320, 214));
    newGamePanel.setLayout(new java.awt.GridLayout(0, 1));

    infoTip_newGame.setBackground(new java.awt.Color(51, 153, 255));
    infoTip_newGame.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    infoTip_newGame.setForeground(new java.awt.Color(255, 255, 255));
    infoTip_newGame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    infoTip_newGame.setText("Enter New Game Info.");
    infoTip_newGame.setAlignmentX(0.5F);
    infoTip_newGame.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
    infoTip_newGame.setOpaque(true);
    newGamePanel.add(infoTip_newGame);

    optionsPanel_newGame.setPreferredSize(new java.awt.Dimension(278, 0));
    optionsPanel_newGame.setLayout(new java.awt.GridBagLayout());

    nameOption_newGame.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 0));

    nameFieldLabel_newGame.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    nameFieldLabel_newGame.setText("Name:");
    nameFieldLabel_newGame.setPreferredSize(new java.awt.Dimension(70, 16));
    nameOption_newGame.add(nameFieldLabel_newGame);

    nameField_newGame.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    nameField_newGame.setPreferredSize(new java.awt.Dimension(140, 25));
    nameOption_newGame.add(nameField_newGame);

    optionsPanel_newGame.add(nameOption_newGame, new java.awt.GridBagConstraints());

    newGamePanel.add(optionsPanel_newGame);

    submissionButtonPanel_newGame.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(153, 153, 153)));
    java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
    flowLayout1.setAlignOnBaseline(true);
    submissionButtonPanel_newGame.setLayout(flowLayout1);

    submitButton__newGame.setText("Submit");
    submitButton__newGame.setPreferredSize(new java.awt.Dimension(75, 25));
    submitButton__newGame.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        submitButton__newGameActionPerformed(evt);
      }
    });
    submissionButtonPanel_newGame.add(submitButton__newGame);

    cancelButton_newGame.setText("Cancel");
    cancelButton_newGame.setPreferredSize(new java.awt.Dimension(75, 25));
    cancelButton_newGame.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelButton_newGameActionPerformed(evt);
      }
    });
    submissionButtonPanel_newGame.add(cancelButton_newGame);

    newGamePanel.add(submissionButtonPanel_newGame);

    fileMenu.setText("File");

    loadGame.setText("Load Game");
    fileMenu.add(loadGame);

    newGame.setText("New Game");
    newGame.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        newGameActionPerformed(evt);
      }
    });
    fileMenu.add(newGame);

    deleteGame.setText("Delete Game");
    fileMenu.add(deleteGame);
    fileMenu.add(gameAndScreenSeperator);

    loadScreen.setText("Load Screen");
    fileMenu.add(loadScreen);

    newScreen.setText("New Screen");
    newScreen.setToolTipText("NewScreen");
    fileMenu.add(newScreen);

    saveScreen.setText("Save Screen");
    fileMenu.add(saveScreen);

    deleteScreen.setText("Delete Screen");
    fileMenu.add(deleteScreen);

    menuBar.add(fileMenu);

    setJMenuBar(menuBar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(40, 40, 40)
        .addComponent(newGamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(52, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(75, 75, 75)
        .addComponent(newGamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(85, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void newGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameActionPerformed
    // TODO add your handling code here:
    newGamePanel.setVisible( true );
  }//GEN-LAST:event_newGameActionPerformed

  private void submitButton__newGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButton__newGameActionPerformed
    // TODO add your handling code here:
    String newGameName = nameField_newGame.getText();
    
    try 
    {
      String gamesFolderPath = "src/main/java/com/ceofyeast/stringgameengine/screeneditor/gamestest/";
      
      File myObj = new File( gamesFolderPath + newGameName + ".json" );
      
      if (myObj.createNewFile()) 
      {
        System.out.println( "File created: " + myObj.getName() );
        
        nameField_newGame.setText( "" );
        
        newGamePanel.setVisible( false );
      } 
      else 
      {
        System.out.println( "File already exists." );
        
        nameField_newGame.setText( "File already exists." );
      }
    } catch (IOException e) {
      System.out.println( "An error occurred." );
      
      e.printStackTrace();
    }
  }//GEN-LAST:event_submitButton__newGameActionPerformed

  private void cancelButton_newGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButton_newGameActionPerformed
    // TODO add your handling code here:
    nameField_newGame.setText( "" );
    
    newGamePanel.setVisible( false );
  }//GEN-LAST:event_cancelButton_newGameActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(ScreenEditorJframeTesting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(ScreenEditorJframeTesting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(ScreenEditorJframeTesting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(ScreenEditorJframeTesting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new ScreenEditorJframeTesting().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton cancelButton_newGame;
  private javax.swing.JMenuItem deleteGame;
  private javax.swing.JMenuItem deleteScreen;
  private javax.swing.JMenu fileMenu;
  private javax.swing.JPopupMenu.Separator gameAndScreenSeperator;
  private javax.swing.JLabel infoTip_newGame;
  private javax.swing.JMenu loadGame;
  private javax.swing.JMenu loadScreen;
  private javax.swing.JMenuBar menuBar;
  private javax.swing.JLabel nameFieldLabel_newGame;
  private javax.swing.JTextField nameField_newGame;
  private javax.swing.JPanel nameOption_newGame;
  private javax.swing.JMenuItem newGame;
  private javax.swing.JPanel newGamePanel;
  private javax.swing.JMenuItem newScreen;
  private javax.swing.JPanel optionsPanel_newGame;
  private javax.swing.JMenuItem saveScreen;
  private javax.swing.JPanel submissionButtonPanel_newGame;
  private javax.swing.JButton submitButton__newGame;
  // End of variables declaration//GEN-END:variables
}
